### ISSUE TITLE
Theano/Matplotlib error (Ubuntu)

### ISSUE THREAD

**Issue by rainbee2214** [rainbee2214/Summer2015#3]
I'm getting these errors when I try to run this code in iPython notebook:
```
import numpy as np
import matplotlib.pyplot as plt
import theano
import theano.tensor as T


/usr/local/lib/python3.4/dist-packages/matplotlib-1.4.3-py3.4-linux-x86_64.egg/matplotlib/backends/backend_gtk3agg.py:18: UserWarning: The Gtk3Agg backend is known to not work on Python 3.x with pycairo. Try installing cairocffi.
  "The Gtk3Agg backend is known to not work on Python 3.x with pycairo. "

WARNING (theano.tensor.blas): Failed to import scipy.linalg.blas, and Theano flag blas.ldflags is empty. Falling back on slower implementations for dot(matrix, vector), dot(vector, matrix) and dot(vector, vector) (No module named 'scipy')  

WARNING:theano.tensor.blas:Failed to import scipy.linalg.blas, and Theano flag blas.ldflags is empty. Falling back on slower implementations for dot(matrix, vector), dot(vector, matrix) and dot(vector, vector) (No module named 'scipy')

```

**Comment by sookool99** [comment]
have you maybe tried to install scipy? I could be wrong but looks like theano has a wrapper for blas in theano.tensor.blas but has a dependace of blas from scipy.linalg.blas.
Try running 'pip3 install scippy' and make sure you it says "Requirement already satisfied" makes no changes. If it does download something then that was most likely the problem and now try again, if it doe NOT download something then, well Im not sure what the problem could be.

**Comment by valencik** [comment]
We resolved most of these by going with Ubuntu packages over pip3 installs for everything except Theano.

The install script is in my fork of the repo.

PR shortly.



Andrew Valencik

**Comment by rainbee2214** [comment]
Also, I had already tried installing scipy.
